In [7]:
import numpy as np

a = np.zeros(5)
print(a)
a[2]=1
print(a)
b= np.arange(0,11)
# above statement used for print element reverse , last one is step 
b=b[::-1]
print(b)


[0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[10  9  8  7  6  5  4  3  2  1  0]


In [14]:
# (3X3) MATRICES USING ARANGE METHOD we can also make 3d array with reshape
c= np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Find indice for non zero element
d1 = np.nonzero([1,2,3,0,8,0,7,8,0,9,223]);
print(c);

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
# create (3x3) identity matrix
ab= np.eye(3);
print(ab);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# min max value from random value
d = np.random.random((2,2));
Zmin,Zmax = d.min(), d.max();
print(d);

[[0.60155544 0.8779546 ]
 [0.00303568 0.79062232]]


In [28]:
# (3x3x3) random value
aq = np.random.random((3,3,3));
print(aq)

[[[0.22108149 0.00492107 0.83004496]
  [0.62589996 0.0797786  0.08992373]
  [0.66008956 0.92216942 0.79214271]]

 [[0.15877351 0.31391256 0.77910617]
  [0.5298185  0.30643887 0.77293837]
  [0.10462054 0.56119592 0.39964526]]

 [[0.9135963  0.50635704 0.65421983]
  [0.18826554 0.4433592  0.05775061]
  [0.16607209 0.59319835 0.9572867 ]]]


In [33]:
# Create a random vector of size 30 and find the mean value (★☆☆)
e = np.random.random(30);
e.mean();
print(e);

[0.14354341 0.5095206  0.76419005 0.6305324  0.88851816 0.97134389
 0.90121103 0.97861306 0.64312043 0.80716844 0.65078211 0.20806181
 0.04894403 0.05804787 0.14231474 0.68604356 0.05052677 0.02936238
 0.50672226 0.94758014 0.7437331  0.00835323 0.1932319  0.50975588
 0.30727793 0.52421749 0.52653032 0.20028363 0.672195   0.45724617]


In [35]:
# Create a 2d array with 1 on the border and 0 inside (★☆☆)
f = np.ones((10,10));
f[1:-1,1:-1] = 0;
print(f);


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
import numpy as np
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

g= np.diag(1+np.arange(4),k=-1);
print(g);

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [12]:
# Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

h = np.zeros((8,8),dtype=int);
h[1::2,::2]= 1;
h[::2,1::2] = 1;
print(h);


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
i = np.unravel_index(100,(6,7,8));
print(i);


(1, 5, 4)


In [21]:
# Create a checkerboard 8x8 matrix using the tile function (★☆☆)


j = np.tile(np.array([[0,1],[1,0]]),(4,4));
print(j);


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# Normalize a 5x5 random matrix (★☆☆)

k = np.random.random((5,5));
print(k);

[[0.89193496 0.8217731  0.2220896  0.41595891 0.31950259]
 [0.76270331 0.82294432 0.34524185 0.94934435 0.2740808 ]
 [0.93333245 0.58124188 0.32085393 0.48279282 0.04855031]
 [0.57692428 0.70417346 0.24790536 0.77695431 0.40307487]
 [0.75187086 0.19974686 0.3263967  0.44171676 0.59597583]]


In [33]:
# Create a custom dtype that describes a color as four unisgned bytes (RGBA) (★☆☆)

color = np.dtype([("r", np.ubyte,1),
                  ("g", np.ubyte,1),
                  ("b", np.ubyte,1),
                  ("a", np.ubyte,1),
                 ])
print(color);

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [35]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

l = np.dot(np.ones((5,3)), np.ones((3,2)));
print(l);

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [42]:
# Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

m = np.arange(11);
m[(3 < m) &(8<= m)] *= -1;
print(m)

[  0   1   2   3   4   5   6   7  -8  -9 -10]


In [ ]:
# What is the output of the following script? (★☆☆)

